import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat} from "next/font/google";
import "./globals.css";
import { montserrat_global as montserrat } from "@/constants";
import { cookies } from "next/headers";
import axios, { AxiosError } from "axios";
import { COOKIE_NAME, TABLES } from "@/constants";
import { createSupabaseUserClient } from "@/types/supabaseClient";
import Footer from "@/components/footer";
import HeaderSelector from "@/components/headers/HeaderSelector";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //placeholder for the backend logic
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <header className='fixed top-0 left-0 w-full shadow z-50'>
          <HeaderSelector />
        </header>
        <div className='pt-20 bg-lightyellow'>
        {children}
        </div>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
