import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderSelector from "@/components/headers/HeaderSelector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //placeholder for the backend logic
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='fixed top-0 left-0 w-full shadow z-50'>
          <HeaderSelector />
        </header>
        <div className='pt-20 bg-lightyellow'>
        {children}
        </div>

        <footer>
          placeholder for footer 
        </footer>
      </body>
    </html>
  );
}
