export const FUSION_BOARD = [
    { name: "Benson Manzano",             position: "President",                                image: "/board/benson.JPG",},
    { name: "Jassy Hsu",                  position: "Internal Vice President",                  image: "/board/jassy.JPG",},
    { name: "Arvin Limjoco",              position: "External Vice President",                  image: "/board/arvin.JPG",},
    { name: "Dommenick Lacuata",          position: "Treasurer",                                image: "/board/nico.JPG",},
    { name: "Lena Sablan",                position: "Secretary",                                image: "/board/lena.JPG",},
    { name: "Emily Tang",                 position: "Academics Co-Director",                    image: "/board/emily.JPG",},
    { name: "Joshua Yalung",              position: "Academics Co-Director",                    image: "/board/josh.JPG",},
    { name: "Kaylee Quinn",               position: "Athletics Co-Director",                    image: "/board/kailee.JPG",},
    { name: "Lorenz Andrei Leonidas",     position: "Athletics Co-Director",                    image: "/board/lorenz.JPG",},
    { name: "Erin Tuscano",               position: "Cultural Director",                        image: "/board/erin.JPG",},
    { name: "Emma Nazareno",              position: "Fundraising Co-Director",                  image: "/board/emma_fundy.JPG",},
    { name: "Dylan Kha",                  position: "Fundraising Co-Director",                  image: "/board/dylan.JPG",},
    { name: "Ella Ligasan",               position: "Media Co-Director",                        image: "/board/ella.JPG",},
    { name: "Samantha Tawatao",           position: "Media Co-Director",                        image: "/board/sam.JPG",},
    { name: "Daniela Herrera",            position: "ProDev Co-Director",                       image: "/board/daniela.JPG",},
    { name: "Jerrick Aguillar",           position: "ProDev Co-Director",                       image: "/board/jerrick.JPG",},
    { name: "Bianca Cataniag",            position: "Publicity Co-Director",                    image: "/board/bianca.JPG",},
    { name: "Emma Narvaez",               position: "Publicity Co-Director",                    image: "/board/emma_pubs.JPG",},
    { name: "Kaitlin Sasot",              position: "Publicity Co-Director",                    image: "/board/kaitlin.JPG",},
    { name: "Ricky Ferriol",              position: "Engineering Project Co-Director",          image: "/board/ricky.JPG",},
    { name: "Anthony Fabros",             position: "Engineering Project Co-Director",          image: "/board/tfab.JPG",},
    { name: "Noah Tizon",                 position: "ICS Project Co-Director",                  image: "/board/noah.JPG",},
    { name: "Sydney Chou",                position: "ICS Project Co-Director",                  image: "/board/sydney.JPG",},
    { name: "Nathan Tran",                position: "Social Co-Director",                       image: "/board/nathan.JPG",},
    { name: "Isaac Cruz",                 position: "Social Co-Director",                       image: "/board/isaac.JPG",},
];